ARG NODE_VERSION=24.13.0-slim

# Stage 1: Dependencies Installation Stage

FROM node:${NODE_VERSION} AS dependencies

WORKDIR /app

COPY package.json  pnpm-lock.yaml* pnpm-workspace.yaml ./

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    corepack enable pnpm && \
    pnpm config set store-dir /pnpm/store && \
    pnpm config set minimum-release-age 0 && \
    pnpm install --frozen-lockfile --ignore-scripts=false

# Stage 2: Build Next.js application in standalone mode

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production

RUN ./node_modules/.bin/next build

# Stage 3: Run Next.js application


FROM node:${NODE_VERSION} AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=builder --chown=node:node /app/public ./public

RUN mkdir .next
RUN chown node:node .next

COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

USER node

EXPOSE 3000

CMD ["node", "server.js"]